### ISSUE TITLE
Bi-temporal planner for other stores

### ISSUE THREAD

**Issue by manojkr19** [cloudera-labs/envelope#43]
Hi, I’m embarking on a new project on cloudera which requires a bi-temporal storage and I luckily stumbled upon Envolope.  I’m so excited to see this framework exists. I see that bi-temporality is only offered in Kudu.  Any plans to extend this to other stores?

Thanks
Manoj

**Comment by jeremybeard** [comment]
Hi Manoj. We don't have plans to do that in the near future. There are considerable semantic differences between the read/write APIs of the various storage engines, so it's a lot of work to add more to the list. Kudu is already the best storage engine in the Cloudera stack for maintaining low latency updates of bi-temporal tables (because it has both fast individual row mutations and fast scans) so hopefully that's the right choice for you anyway.

**Comment by manojkr19** [comment]
Thanks Jeremy!
